export default interface WebNFT {
  modelType: string,
  gameDate: Date,
  fanPoints: number,
  position: string,
  year: string,
  isVariant: boolean,
  team: string,
  seriesName: string,
  seriesId: number,
  opponent: string,
  description: string,
  rarity: string,
  currentSupply: number,
  maxSupply: number,
  owner: string,
  name: string,
  serialNumber: number,
  link: string,
  image: string,
  dGoodId: number,
  buildingType: string,
  homeTeam: string,
  propertyId: number,
  fullAddress: string,

  isVariantFilter: number,
  category: string
}